server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://192168.147.129:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: admin

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl